services:
  hapi:
    container_name: hapi
    image: "hapiproject/hapi:v7.4.0"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yml
    volumes:
      - ./app:/opt/app
    environment:
      - COMPOSE_PROJECT_NAME=wada-list-cds
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi

configs:
  hapi:
     file: ./hapi.application.yml
