services:
  hapi:
    container_name: hapi
    image: "hapiproject/hapi:v7.4.0"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yml
    volumes:
      - ./h2:/h2
    environment:
      - COMPOSE_PROJECT_NAME=wada-list-cds

configs:
  hapi:
     file: ./hapi.application.yml
